name: 'Send SystemInstance Info to Enov8'
description: 'Send version and resource name to Enov8 SystemInstance API'
inputs:
  version:
    description: 'Version to be sent'
    required: true
  resource_name:
    description: 'Resource name (e.g., GDW (DEV))'
    required: true
  user_id:
    description: 'Enov8 user-id'
    required: true
  app_id:
    description: 'Enov8 app-id'
    required: true
  app_key:
    description: 'Enov8 app-key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'