name: Send Enov8 Update (Environment Scoped)

on:
  workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest
    environment: production   # 🗝️ This enables the secrets
    steps:
      - name: Use Enov8 Secure Action
        uses: hpashok24/enov8-send-environment-info-secure@v1
        env:
          ENOV8_APP_ID: ${{ secrets.ENOV8_APP_ID }}
          ENOV8_APP_KEY: ${{ secrets.ENOV8_APP_KEY }}
          ENOV8_BASE_URL: ${{ secrets.ENOV8_BASE_URL }}
        with:
          version: "18"
          system: "GDW"
          environment: "Dev"
