name: Test Enov8 Action

on:
  workflow_dispatch:

jobs:
  test-enov8:
    runs-on: ubuntu-latest
    steps:
      - name: Send version info to Enov8
        uses: hpashok24/enov8-send-instance@v1
        with:
          system: "GDW (DEV)"
          environment: "DEV Env"
          version: "17.19"
          app_id: ${{ secrets.ENOV8_APP_ID }}
          app_key: ${{ secrets.ENOV8_APP_KEY }}
          enov8_url: ${{ secrets.ENOV8_URL }}
